- type: job
  id: MedicalDoctor
  name: Physician
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 14400 #4 hrs
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  - Paramedic # DeltaV - Add Paramedic access
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 1.75

- type: startingGear
  id: DoctorGear
  subGear:
  - DoctorPlasmamanGear
  equipment:
    jumpsuit: UniformScrubsColorBlack
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesBootsLaceup
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    hat: ClothingPhysicianHood
    mask: ClothingPhysicianMask
    neck: ClothingPhysicianCollar
    gloves: ClothingPhysicianGloves
    outerClothing: ClothingPhysicianRobe
  innerClothingSkirt: UniformScrubsColorBlack
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled

- type: startingGear
  id: DoctorPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMedicalDoctor
    head: ClothingHeadEnvirohelmMedicalDoctor
    gloves: ClothingHandsGlovesEnviroglovesWhite
