- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobAtmosphericTechnician
      min: 21600 #6 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobStationEngineer
      min: 21600 #6 hrs
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 216000 # 60 hrs
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed
  special:
    - !type:AddComponentSpecial
    components:
      - type: Statistics
        attributes:
          Strength: 10
          Dexterity: 11
          Intelligence: 13
          Will: 9
        skills:
          Electrician: 2
          Mechanic: 2
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  subGear:
  - StationEngineerPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtSeniorEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
